# Generated by Django 2.2.5 on 2019-09-13 07:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0006_auto_20190913_0734'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follower',
            new_name='Following',
        ),
    ]
