# Generated by Django 2.2.5 on 2019-09-13 07:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0007_auto_20190913_0735'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Following',
            new_name='Follow',
        ),
    ]
