# Generated by Django 2.2.5 on 2019-09-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_question_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='categories',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
