# Generated by Django 2.2.5 on 2019-09-16 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_question_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='categories',
        ),
    ]
