# Generated by Django 2.2.5 on 2019-09-21 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_question_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer',
            new_name='question',
        ),
    ]
